/* --- NEW MIGRATIONS FOR COLOR SUPPORT --- */
ALTER TABLE public.user_tags ADD COLUMN IF NOT EXISTS color text DEFAULT '#3B82F6';
ALTER TABLE public.sessions ADD COLUMN IF NOT EXISTS color text DEFAULT '#3B82F6';
