-- Keep internal trigger functions inaccessible through the Data API.
ALTER FUNCTION public.handle_new_user() SET search_path = '';
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;

-- Account deletion remains available to the signed-in owner only.
-- Its body already checks auth.uid() before deleting that owner's records.
ALTER FUNCTION public.delete_user_data() SET search_path = '';
REVOKE EXECUTE ON FUNCTION public.delete_user_data() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_user_data() TO authenticated;

-- Existing public images keep their read permissions. Writes are restricted
-- to the user's UUID directory, matching the paths generated by the app.
DROP POLICY IF EXISTS "Authenticated Upload" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Upload Sessions" ON storage.objects;
DROP POLICY IF EXISTS "Authenticated Delete Sessions" ON storage.objects;

CREATE POLICY "Owners upload session and venue images"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id IN ('sessions', 'venues') AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

CREATE POLICY "Owners update session and venue images"
ON storage.objects FOR UPDATE TO authenticated
USING (bucket_id IN ('sessions', 'venues') AND (storage.foldername(name))[1] = (SELECT auth.uid())::text)
WITH CHECK (bucket_id IN ('sessions', 'venues') AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);

CREATE POLICY "Owners delete session and venue images"
ON storage.objects FOR DELETE TO authenticated
USING (bucket_id IN ('sessions', 'venues') AND (storage.foldername(name))[1] = (SELECT auth.uid())::text);
